api/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

import views

router = DefaultRouter()
router.register(r'^users', views.UserViewSet)
router.register(r'^questions', views.QuestionViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

hello/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('polls.urls')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls', namespace='api')),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# url(r'^$', views.index, name='index'),
	# url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^user/register/$', views.user_register, name='register'),
	url(r'^user/login/$', views.user_login, name='login'),
	url(r'^user/logout/$', views.user_logout, name='logout'),
	url(r'^user/profile/$', views.user_profile, name='profile'),
]

handler404 = 'polls.views.custom_404'

api/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolen = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/models/Choice.py
from .__shared_imports import *

from .Question import Question


class Choice(models.Model):

    class Meta:
        app_label = 'polls'

    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/models/Question.py
from .__shared_imports import *

import datetime
from django.utils import timezone


class Question(models.Model):

    class Meta:
        app_label = 'polls'

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    owner = models.ForeignKey('auth.User', related_name='questions')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolen = True
    was_published_recently.short_description = 'Published recently?'

    @classmethod
    def get(cls, pk=0):
        if pk > 0:
            return cls.objects.get(pk=pk)
        return cls.objects.all()

polls/models/__shared_imports.py
from django.db import models

api/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

# Create your views here.

# from django.http import Http404
# from rest_framework.views import APIView
# from rest_framework.response import Response
# from rest_framework import status

from rest_framework import generics
from rest_framework import permissions

from rest_framework import viewsets

from polls.models.Question import Question
from .serializers.question_serializer import QuestionSerializer
from .serializers.user_serializer import UserSerializer
from .permissions import IsOwnerOrReadOnly
from .auth import CsrfExemptSessionAuthentication

class QuestionViewSet(viewsets.ModelViewSet):
    '''
    This automatically provides a `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    '''
    queryset = Question.get()
    serializer_class = QuestionSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly)
    authentication_classes = (CsrfExemptSessionAuthentication, )

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

polls/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models.Choice import Choice
from .models.Question import Question


def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    data = {
        'latest_questions': latest_questions,
    }
    return render(request, 'polls/index.html', data)


def detail(request, question_id):
    # try:
    # 	question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    # 	raise Http404("Question does not exist")

    # shortcut
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def user_register(request):
    # redo with Django forms
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']

        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        return HttpResponseRedirect(reverse('polls:index'))
    else:
        return render(request, 'polls/register.html', {})


def user_login(request):
    error = None
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/polls/user/profile')
            else:
                return HttpResponse("Account has been disabled")
        else:
            error = "Wrong username/password combination"
    return render(request, 'polls/login.html', {'error': error})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/polls/user/login')


@login_required(login_url='/polls/user/login')
def user_profile(request):
    return render(request, 'polls/user_profile.html', {})


def custom_404(request):
    return render(request, 'polls/404.html')

# Django generic views


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        '''Return the last five questions'''
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

polls/templates/polls/detail.html
{% extends 'polls/layout.html' %}

{% block content %}

	<h5>{{ question.question_text }}</h5>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
		{% endfor %}
		<input type="submit" value="Vote" class="btn waves-effect waves-light"/>
	</form>

{% endblock %}

polls/templates/polls/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Poll+</title>
	{% load staticfiles %}

	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap.paper.css' %}" /> -->
	<link rel="stylesheet" type="text/css" href="{% static 'polls/materialize/css/materialize.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
<div class="main">

	{% block nav %}
	<ul id="userdd" class="dropdown-content">
		<li><a href="{% url 'polls:logout' %}">Logout</a></li>
	</ul>
	<nav class="white" role="navigation">
	    <div class="nav-wrapper container">
	      <a id="logo-container" href="/polls" class="brand-logo">Poll+</a>
	      <ul class="right hide-on-med-and-down">
	      {% if request.user.username %}
	      	<li><a class="dropdown-button" href="#!" data-activates="userdd">{{ request.user.first_name }}<i class="material-icons right">arrow_drop_down</i></a></li>
	      {% else %}
	        <li><a href="{% url 'polls:login' %}">Login</a></li>
	      {% endif %}
	      </ul>

	      <ul id="nav-mobile" class="side-nav">
	        <li><a href="{% url 'polls:login' %}">Login</a></li>
	      </ul>
	      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
	    </div>
  	</nav>
  	{% endblock %}


	<div class="container">

	    {% block content %}

	    {% endblock %}
	</div>


</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<!-- <script type="text/javascript" src="{% static 'polls/bootstrap.min.js' %}"></script> -->
<script type="text/javascript" src="{% static 'polls/materialize/js/materialize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'polls/script.js' %}"></script>

{% block js %}
<!-- any extra page-specific scripts -->

{% endblock %}

</body>
</html>

polls/templates/polls/login.html
{% extends 'polls/layout.html' %}

{% block content %}

	<div class="row">
		<h4>User Login</h4>
		
		<form class="col s12" action="" method="post">
			{% csrf_token %}
			<div class="row col s6">
				<div class="input-field">
		          <input name="username" id="first_name" type="text" class="validate" required>
		          <label for="username">Username</label>
		        </div>
		        <div class="input-field">
		          <input name="password" id="password" type="password" class="validate" required>
		          <label for="password">Password</label>
		        </div>

		        <button class="waves-effect waves-light btn" type="submit">
		    		Login
		    	</button>
		    </div>

		</form>
	</div>

{% endblock %}

{% block js %}

        {% if error %}
            <!-- <div class="alert alert-warning">{{ error }}</div> -->
            <script type="text/javascript">
                Materialize.toast('{{ error }}', 4000)
            </script>
        {% endif %}
        
{% endblock %}

polls/templates/polls/register.html
{% extends 'polls/layout.html' %}

{% block content %}

	<div class="row">
		<h4>User Signup</h4>
		
		<form class="col s12" action="" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="input-field col s6">
		          <input name="first_name" id="first_name" type="text" class="validate" required>
		          <label for="first_name">First Name</label>
		        </div>
		        <div class="input-field col s6">
		          <input name="last_name" id="last_name" type="text" class="validate" required>
		          <label for="last_name">Last Name</label>
		        </div>
		    </div>

		    <div class="row">
		    	<div class="input-field col s6">
		          <input name="email" id="email" type="text" class="validate" required>
		          <label for="email">Email</label>
		        </div>
		        <div class="input-field col s6">
		          <input name="username" id="username" type="text" class="validate" required>
		          <label for="username">Username</label>
		        </div>

		    </div>

		    <div class="row">
		    	<div class="input-field col s6">
		          <input name="password" id="password" type="password" class="validate" required>
		          <label for="password">Password</label>
		        </div>
		        <div class="input-field col s6">
		          <input name="password_confirm" id="password_confirm" type="password" class="validate" required>
		          <label for="password_confirm">Confirm Password</label>
		        </div>

		    </div>

		    <button class="waves-effect waves-light btn-large" type="submit">
		    	Sign Up
		    </button>
		</form>
	</div>

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/layout.html' %}

{% block content %}

	<h5>{{ question.question_text }}</h5>

	<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
	</ul>

	<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}

polls/templates/polls/user_profile.html
{% extends 'polls/layout.html' %}

{% block content %}

	<div class="row">
		<h4>User Profile</h4>
		
	</div>

{% endblock %}